### ISSUE TITLE
SetMaxHealthPlayer

### ISSUE THREAD

**Issue by t0pd3v1c3** [OxideMod/Oxide.Rust#109]
I need a similar patch like this https://github.com/OxideMod/Oxide.Rust/commit/da307eae8095fee1572f653e8202062e9d884a78 but on BasePlayer, so that you can change the maximum amount of player health.

**Comment by lukespragg** [comment]
You can already do so natively in Rust.

**Comment by t0pd3v1c3** [comment]
What function is used?

**Comment by lukespragg** [comment]
Just set the _maxhealth field.

**Comment by t0pd3v1c3** [comment]
@lukespragg, of course I tried to set a HP for the player, but still it is set to 100: 
```
player._health = 1000;
player._maxHealth = 1000;
```
The https://github.com/OxideMod/Oxide.Rust/commit/da307eae8095fee1572f653e8202062e9d884a78 changes MaxHealth() for NPCMurderer. Look at screenshot:
![image](https://user-images.githubusercontent.com/26054454/45209476-d0567b80-b295-11e8-8338-67f5fcad16f6.png)
This is from Assembly-CSharp.dll.

**Comment by lukespragg** [comment]
Looks like I somehow missed it then, as when I was looking it was already using _maxHealth for BasePlayer, so I must have looked at something else. I'll check again shortly and add a patch for it. :)
