### ISSUE TITLE
OnItemDeployed not working?

### ISSUE THREAD

**Issue by jacobcoughenour** [OxideMod/Oxide.Rust#22]
OnItemDeployed hook is not working for me.
Am I missing something?
```
void OnItemDeployed(Deployer deployer, BaseEntity entity) {
    Puts("OnItemDeployed works!");
}
```

**Comment by lukespragg** [comment]
What exactly are you trying to deploy with it? Not all objects/entities are deployed the same way. The hook hasn't changed, so it most likely works just fine for the intended entities that get deployed.

**Comment by jacobcoughenour** [comment]
I needed a hook for when a player places something like a storage container, tool cupboard, or vending machine.  Mughisi pointed out that OnEntityBuilt is the hook I should use on the Discord.
Thanks!
