### ISSUE TITLE
Missing NuGet Packages?

### ISSUE THREAD

**Issue by term1nal** [OxideMod/Oxide.Rust#35]
I don't appear to be able to compile myself from source, as all of the NuGet packages (Oxide.Core, Oxide.CSharp, Oxide.MySql, Oxide.References, Oxide.SQLite, and Oxide.Unity) are missing. How do I acquire these or point the solution to the correct location? The readme for Oxide.Rust says these are bundled.

**Comment by lukespragg** [comment]
You would need to add the NuGet feed that we use, which can be found in he nuget.config file in each repo.

**Comment by term1nal** [comment]
Is it possible this information could be added to the readme (as well as how to accomplish this, for those who are new with this particular development environment)?

**Comment by lukespragg** [comment]
Yes, the readme is currently a bit outdated, but new ones are on the way for every repo.

**Comment by term1nal** [comment]
It appears as though it was freaking out because there was a "local" source defined. Also, I had to remove the references then re-add them through the UI, which was able to install the latest version an satisfy the dependency.

I had to do the same with all of the assembly references as well, because when you first open the solution, all of the assembly references were missing.

When I went into add references and checked the boxes for the various assemblies in the list (to ostensibly tell it where the .dlls were located), it declared "The reference is invalid or unsupported" for every single one until I "removed" the reference from the solution then re-added it again.

**Comment by lukespragg** [comment]
If you did all of that, you did it wrong. The actual game references are acquired by building the project as they are downloaded via Steam.

**Comment by term1nal** [comment]
Well they were all showing as yellow exclamations (which lead to thousands of errors for missing references), so I pointed the references to my locally installed Rust server's copies of the DLLs.

**Comment by lukespragg** [comment]
They won’t exist until the project is build and it downloads them. Visual Studio may not recognize them automatically until the next build though.

**Comment by term1nal** [comment]
Here's what I get when I attempt to build the package (fresh downloaded .zip from github). These are never satisfied no matter how many times I run "build".

Severity    Code    Description Project File    Line    Suppression State
    Warning MSB3245 Could not resolve this reference. Could not locate the assembly "Facepunch.Network". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.    Oxide.Rust  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets  2041    
    Warning MSB3245 Could not resolve this reference. Could not locate the assembly "Assembly-CSharp". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.  Oxide.Rust  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets  2041    
    Warning MSB3245 Could not resolve this reference. Could not locate the assembly "Assembly-CSharp-firstpass". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.    Oxide.Rust  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets  2041    
    Warning MSB3245 Could not resolve this reference. Could not locate the assembly "Facepunch.Console". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.    Oxide.Rust  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets  2041    
    Warning MSB3245 Could not resolve this reference. Could not locate the assembly "Facepunch.Rcon". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.   Oxide.Rust  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets  2041    
    Warning MSB3245 Could not resolve this reference. Could not locate the assembly "Facepunch.Steamworks". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. Oxide.Rust  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets  2041    
    Warning MSB3245 Could not resolve this reference. Could not locate the assembly "Facepunch.System". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. Oxide.Rust  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets  2041    
    Warning MSB3245 Could not resolve this reference. Could not locate the assembly "Facepunch.Unity". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.  Oxide.Rust  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets  2041    
    Warning MSB3245 Could not resolve this reference. Could not locate the assembly "Facepunch.UnityEngine". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.    Oxide.Rust  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets  2041    
    Warning MSB3245 Could not resolve this reference. Could not locate the assembly "Rust.Data". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.    Oxide.Rust  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets  2041    
    Warning MSB3245 Could not resolve this reference. Could not locate the assembly "Rust.Global". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.  Oxide.Rust  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets  2041    
    Warning MSB3245 Could not resolve this reference. Could not locate the assembly "UnityEngine". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.  Oxide.Rust  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets  2041    
    Warning MSB3245 Could not resolve this reference. Could not locate the assembly "UnityEngine.UI". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.   Oxide.Rust  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets  2041    
    Warning MSB3245 Could not resolve this reference. Could not locate the assembly "websocket-sharp". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.  Oxide.Rust  C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets  2041    
    Error       Assets file 'C:\Users\Owner\Desktop\Oxide.Rust-develop\src\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.   Oxide.Rust  C:\Program Files\dotnet\sdk\2.1.4\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets    327 
    Error       Assets file 'C:\Users\Owner\Desktop\Oxide.Rust-develop\src\obj\project.assets.json' not found. Run a NuGet package restore to generate this file.   Oxide.Rust  C:\Program Files\dotnet\sdk\2.1.4\Sdks\Microsoft.NET.Sdk\build\Microsoft.PackageDependencyResolution.targets    167

**Comment by lukespragg** [comment]
That means Steam failed to download them then.

**Comment by term1nal** [comment]
Do I need steam client installed is that why? (The VM I am using to run Visual Studio on doesn't have Steam. I run Linux as my host OS).

**Comment by lukespragg** [comment]
No, the Steam.ps1 file is ran when you build. If you don’t have PowerShell 5.x installed, it won’t run.

**Comment by thibmo** [comment]
The last comment of Luke is correct.

Looking at the output, one can spot instantly what the issue really is. :)
```PowerShell
The term 'Invoke-WebRequest' is not recognized as the name of a cmdlet, function, script file, or operable program.
```

The PowerShell(PS) method 'Invoke-WebRequest' has been added in PSv3.0.
This is the default version for Windows 8+ (There is an installer for Win 7).
If you want to know which exact version you have, just execute the following in a PS console:
```PowerShell
$PSVersionTable
```

More info:
- [PS per OS](https://4sysops.com/archives/powershell-versions-and-their-windows-version/#powershell-and-windows-versions) on 4sysops.com
- [Invoke-WebRequest](https://ss64.com/ps/invoke-webrequest.html) on SS64.com
- [Invoke-WebRequest](http://www.computerperformance.co.uk/powershell/powershell_invoke_webrequest.htm) on computerperformance.co.uk
