### ISSUE TITLE
oxide no longer outputs to console(rcon) + other various issues

### ISSUE THREAD

**Issue by fosspill** [OxideMod/Oxide.Rust#60]
Seems like the last update introduced some weirdness for us.

The most critical one is that running anything related to oxide will not yield any output (other than a newline) in rcon console:
```
> oxide.version

```
```
> oxide.plugins

```
```
> oxide.load PluginName

```

**Comment by lukespragg** [comment]
This has been resolved already, please update again. If you still have issues, please use our forums at https://oxidemod.org.

**Comment by fosspill** [comment]
Thank you, but there is no new update out?

**Comment by lukespragg** [comment]
The same build was updated with a temp fix shortly after it was released until a new build is made.
