### ISSUE TITLE
New server-controlled vendingmachines running out of stock when oxidemod is enabled?

### ISSUE THREAD

**Issue by fosspill** [OxideMod/Oxide.Rust#77]
The vending machines at the new Compound monument seems to be running out of stock when oxide is active.

Ref: https://old.reddit.com/r/playrust/comments/8gsrrz/compound_update_official_bug_reporting_megathread/dyehwmm/

Using VendingManager to set the "Bottomless" flag fixes the issue, but this shouldn't be needed.

**Comment by lukespragg** [comment]
Oxide doesn't modify this in any way without plugins doing so.
