### ISSUE TITLE
Issue openning Oxide.Rust.sln

### ISSUE THREAD

**Issue by Dyceman** [OxideMod/Oxide.Rust#88]
`Oxide.Rust.sln: Visual Studio needs to make non-functional changes to this project in order to enable the project to open in released versions of Visual Studio newer than Visual Studio 2010 SP1 without impacting project behavior.`

I am using VS 2017

**Comment by lukespragg** [comment]
I haven't encountered that, so can't really fix what isn't reproducible.

**Comment by Dyceman** [comment]
I also see this, `error  : The SDK 'Microsoft.NET.Sdk' specified could not be found.` What version of the SDK are you guys using? The latest?

**Comment by lukespragg** [comment]
See https://github.com/Microsoft/msbuild/issues/2532#issuecomment-343578403.

**Comment by Dyceman** [comment]
I did what was told in the link sent and I am still having this issue `error  : The SDK 'Microsoft.NET.Sdk' specified could not be found.`

**Comment by lukespragg** [comment]
I would suspect that .NET Core Build Tools still isn't installed then.

**Comment by Dyceman** [comment]
What version of SDK is used?

**Comment by lukespragg** [comment]
We don't target any specific SDK, that is used for the build tools/targets. So whatever Visual Studio requires.
